
const movies = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Fight Club",
    "The Matrix",
    "Gladiator",
    "The Silence of the Lambs",
    "Interstellar",
    "Schindler's List",
    "Saving Private Ryan",
    "Titanic",
    "Avengers: Endgame",
    "Jurassic Park",
    "The Lion King (1994)",
    "Star Wars: Episode IV - A New Hope",
    "Back to the Future",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "Harry Potter and the Sorcerer’s Stone",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Spider-Man: No Way Home",
    "Iron Man",
    "Deadpool",
    "The Wolf of Wall Street",
    "Joker",
    "Black Panther",
    "Guardians of the Galaxy",
    "Doctor Strange",
    "Dune (2021)",
    "Mad Max: Fury Road",
    "The Social Network",
    "Parasite",
    "Whiplash",
    "The Prestige",
    "12 Angry Men",
    "Goodfellas",
    "The Departed",
    "Se7en",
    "Django Unchained",
    "Inglourious Basterds",
    "The Grand Budapest Hotel",
    "The Green Mile",
    "1917",
    "A Beautiful Mind",
    "La La Land",
    "Casablanca",
    "Spirited Away",
    "My Neighbor Totoro",
    "Your Name (Kimi no Na wa)",
    "Weathering with You",
    "Howl's Moving Castle",
    "Princess Mononoke",
    "Grave of the Fireflies",
    "Akira",
    "Ghost in the Shell",
    "Nausicaä of the Valley of the Wind",
    "The Wind Rises",
    "Kiki's Delivery Service",
    "Castle in the Sky",
    "Paprika",
    "Perfect Blue",
    "A Silent Voice (Koe no Katachi)",
    "The Girl Who Leapt Through Time",
    "Wolf Children",
    "5 Centimeters per Second",
    "Children Who Chase Lost Voices",
    "The Tale of the Princess Kaguya",
    "When Marnie Was There",
    "Ponyo",
    "Millennium Actress",
    "Summer Wars",
    "Redline",
    "Sword Art Online: Ordinal Scale",
    "Demon Slayer: Mugen Train",
    "Jujutsu Kaisen 0",
    "One Piece: Stampede",
    "One Piece Film: Red",
    "Dragon Ball Super: Broly",
    "Dragon Ball Z: Resurrection 'F'",
    "Naruto Shippuden the Movie: Road to Ninja",
    "Boruto: Naruto the Movie",
    "Pokémon: The First Movie",
    "Pokémon: The Power of Us",
    "Digimon Adventure: Last Evolution Kizuna",
    "Evangelion: 1.0 You Are (Not) Alone",
    "Evangelion: 2.0 You Can (Not) Advance",
    "Evangelion: 3.0 You Can (Not) Redo",
    "Evangelion: 3.0+1.0 Thrice Upon a Time",
    "Lupin III: The Castle of Cagliostro",
    "Ninja Scroll",
    "Tokyo Godfathers",
    "Violet Evergarden: The Movie",
    "Belle",
    "Bubble",
    "The Boy and the Beast",
    "The Secret World of Arrietty"
];

export default movies;